# Generated by Django 5.0 on 2024-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
